[package]
name = "cadit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.19.0"
egui_dock = { path = "../../../egui_dock", features = ["serde"] }
thiserror = "1.0.37"
