[package]
name = "window"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui_winit_vulkano = { path = "../../../egui_winit_vulkano" }
winit = "0.27.5"
vulkano-util = "0.32"
vulkano = "0.32"
